# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8244ca1c66eaddbaa301330bc30516dfae7a382de550ff05cada724f08a2c50c5e4ea1157776d08eb3be1a218c89c4adbc4ced87f1c286d3e9f3ffb7d26e1f09

test:
  secret_key_base: a07a02a959f29c46ae2d143561eaa9d908f90a7af955013667864e210aaaa8107d98aaedfb674c9f6d2a63819ddbcc6fd29a01f69101f83a8581060324f451d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
